## PostgreSQL
spring:
  datasource:
#   url: jdbc:mysql://localhost:3306/todolist
    url: jdbc:h2:mem:todolist
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create

spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES: true